controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5 # Tốc độ robot không hỗ trợ > 5 m/s
    min_theta_velocity_threshold: 0.001 #(rad/s)
    failure_tolerance: 0.3
    odom_topic: /nhatbot/odom
    controller_plugins: ["FollowPath", "PurePursuit"]
    goal_checker_plugins: ["general_goal_checker"] # Supervising controller doesn't fail and is not blocked, guarantee that the robot is making progress
    progress_checker_plugins: "progress_checker"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      stateful: true
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

    FollowPath:
      plugin: "nhatbot_controller::PDMotionPlanner"
      kp: 2.0
      kd: 0.1
      max_linear_velocity: 0.3
      max_angular_velocity: 0.3
      step_size: 0.2

    PurePursuit:
      plugin: "nhatbot_controller::PurePursuit"
      look_ahead_distance: 0.5
      max_linear_velocity: 0.3
      max_angular_velocity: 0.3

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: false
      robot_radius: 0.255
      resolution: 0.05
      always_send_full_costmap: True
      rolling_window: true
      width: 3
      height: 3

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan # observation source is the scan
        scan: # Specific configuration
          topic: /scan_filtered
          data_type: "LaserScan"
          max_obstacle_height: 2.0
          clearing: True
          marking: True # Enables the usage of the Bresenham algorithm that clears the cells of the map where no obstacles are detected
          combination_method: 1
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.52 # At least >= robot_radius (55cm)
