planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: false
    planner_plugins: ["GridBased_DijkstraPlanner_Smoother", "GridBased_AStarPlanner_Smoother", "GridBased_SmacPlanner2D_nav2", "GridBased_SmacPlannerHybrid_nav2", GridBased_ThetaStarPlanner_nav2]


    GridBased_ThetaStarPlanner_nav2:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 2.0


    GridBased_SmacPlannerHybrid_nav2:
      plugin: "nav2_smac_planner/SmacPlannerHybrid" 
      downsample_costmap: false          
      downsampling_factor: 1             
      tolerance: 0.25                    
      allow_unknown: true               
      max_iterations: 1000000            
      max_on_approach_iterations: 1000    
      max_planning_time: 5.0            
      motion_model_for_search: "REEDS_SHEPP"    # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 72         
      analytic_expansion_ratio: 3.5      
      analytic_expansion_max_length: 3.0 
      analytic_expansion_max_cost: 200.0  
      analytic_expansion_max_cost_override: false  
      minimum_turning_radius: 0.40       
      reverse_penalty: 2.0               
      change_penalty: 0.0                
      non_straight_penalty: 1.2           
      cost_penalty: 2.0                  
      lookup_table_size: 20.0            
      cache_obstacle_heuristic: false    
      debug_visualizations: false        
      use_quadratic_cost_penalty: False
      downsample_obstacle_heuristic: True
      allow_primitive_interpolation: False
      coarse_search_resolution: 4         
      goal_heading_mode: "DEFAULT"        # DEFAULT, BIDIRECTIONAL, ALL_DIRECTION
      smooth_path: True                  
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2

    GridBased_DijkstraPlanner_Smoother:
      plugin: "nhatbot_planning::DijkstraPlanner_Smoother"


    GridBased_AStarPlanner_Smoother:
      plugin: "nhatbot_planning::AStarPlanner_Smoother"


    GridBased_SmacPlanner2D_nav2:
      plugin: "nav2_smac_planner/SmacPlanner2D" 
      tolerance: 0.125 
      downsample_costmap: false 
      downsampling_factor: 1 
      allow_unknown: true 
      max_iterations: 1000000 
      max_on_approach_iterations: 1000 
      max_planning_time: 2.0
      cost_travel_multiplier: 2.0 
      use_final_approach_orientation: false 
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      robot_radius: 0.255
      resolution: 0.05
      always_send_full_costmap: True
      track_unknown_space: true

      plugins: ["static_layer", "obstacle_layer", inflation_layer]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: /map
        map_subscribe_transient_local: True

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan 
        scan: 
          topic: /scan
          data_type: "LaserScan"
          max_obstacle_height: 2.0
          clearing: True
          marking: True # Enables the usage of the Bresham al that clears the cells of the map where no obstacles are detected
          combination_method: 1
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55 # At least >= robot_radius (55cm)

        
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan_filtered
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

