scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -2.0943951024 # -120
        upper_angle: 2.0943951024 # 120
