twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic: /input_joy/cmd_vel
        timeout: 0.2
        priority: 99
      keyboard:
        topic: /key_vel
        timeout: 0.5
        priority: 90

      navigation:
        topic: /cmd_vel
        timeout: 0.5
        priority: 10
